// Stack myStack = new Stack();

// myStack.push(7)
// myStack.push(8)
// myStack.push(6)
// myStack.pop()
// myStack.push(5)
// myStack.push(3)
// myStack.pop()

// Stack newStack = new Stack()

// newStack.push(12)
// newStack.push(23)
// newStack.pop()
// newStack.push(34)
// newStack.push(45)
// newStack.push(56)
// newStack.pop()
// newStack.pop()
// newStack.pop()
// newStack.push(67)
// newStack.pop()
// newStack.push(78)
// newStack.push(89)
// newStack.pop()